name: covid19
channels:
    - conda-forge
dependencies:
    - python=3.7.1
    - numpy
    - matplotlib
    - pandas
    - pip
    - jupyter
    - requests
    - pip:
        - seaborn
        - jupyter_contrib_nbextensions
        - jupyter_nbextensions_configurator
        - countryinfo
        - geonamescache
        - ipywidgets
